### ISSUE TITLE
아래처럼 수정해보면 어떰?

### ISSUE THREAD

**Issue by kjhok1811** [vitamaxDH/field-cryptor-java#6]
https://github.com/vitamaxDH/field-cryptor-java/blob/864562b4be798a0e35c227aa3ee4b01ad2ee8599/src/main/java/com/max/fieldcryptor/ReflectionUtils.java#L47

Field field = getFields(t).stream().filter(field -> field.getName().equals(fieldName)).findFirst().orElse(null);

if (field != null) {
   field.setAccessible(Boolean.TRUE);
}

**Comment by vitamaxDH** [comment]
- done on b5272034291850587a90248c736647768f384a9b
