### ISSUE TITLE
코드리펙토링

### ISSUE THREAD

**Issue by kjhok1811** [vitamaxDH/field-cryptor-java#7]
https://github.com/vitamaxDH/field-cryptor-java/blob/864562b4be798a0e35c227aa3ee4b01ad2ee8599/src/main/java/com/max/fieldcryptor/ReflectionUtils.java#L33

return Arrays.stream(classes).filter(clazz -> clazz == field.getType()).count() == 1;

**Comment by vitamaxDH** [comment]
- 기존 로직과 동일하다고 판단됩니다
