### ISSUE TITLE
root cause throwing exception

### ISSUE THREAD

**Issue by kjhok1811** [vitamaxDH/field-cryptor-java#8]
https://github.com/vitamaxDH/field-cryptor-java/blob/864562b4be798a0e35c227aa3ee4b01ad2ee8599/src/main/java/com/max/fieldcryptor/FieldCryptorUtils.java#L144

throw new RuntimeException(e);로 하죠
예외가 발생되었을 때 추적이 힘들듯

**Comment by vitamaxDH** [comment]
Exception 처리가 누락되어있네요 감사합니다

**Comment by vitamaxDH** [comment]
- 현재 사용중이지 않은 메서드들은 주석처리하였습니다. 후에 살펴볼 수 있도록 하겠습니다.
